### ISSUE TITLE
Prevent "Prototype Caching is enabled" warning?

### ISSUE THREAD

**Issue by moon6969** [justarandomgeek/vscode-factoriomod-debug#61]
I'm debugging with a large number of prototypes at the moment, so often have the prototype caching enabled to speed the launch. 

Everytime I debug in vscode I get the "Prototype Caching is enabled" warning and click "Continue anyway"... it never seems to fail.

What please would be the symptoms of "conflicts with the final portion of debugger initialisation"?

Is there a way to prevent the warning?
If not, could we please have a "remember my choice" option or launch.json option to prevent the warning?
![FactorioDebuggerProtoWarning](https://user-images.githubusercontent.com/30491315/173556969-5aeca124-076c-4023-adb2-3da75eb11108.png)

**Comment by justarandomgeek** [comment]
If it's working when you hit continue, then the caching isn't doing anything for you anyway, presumably because you're continuing to change prototypes and thus needing them reloaded anyway. When the cache is actually active, it completely skips settings & data stages, which deprives me of any early chances to get various information i need from factorio about what mods are running etc
